version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart:
      always

  nginx:
    image:
      nginx
    restart:
      always
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    links:
      - web
    environment:
      - NGINX_PORT=80
      - nginx.conf

