version: '3'

services:
  server:
    image: nginx:alpine
    restart: always
    ports:
      - 443:443
    volumes:
      - ./data:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./TSL:/etc/nginx/TSL